#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [2]:
import pandas as pd
df = pd.read_csv('data/supermarket_sales.csv')
df.head(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,C,Naypyitaw,Normal,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,A,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,17:15,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,B,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,13:27,Credit card,164.52,4.761905,8.2260,5.9

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [3]:
df.groupby('Branch')['gross income'].sum().sort_values(ascending = False)

Branch
C    5265.1765
A    5057.1605
B    5057.0320
Name: gross income, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [4]:
df.groupby(['City' , 'Branch'])['gross income'].sum().sort_values(ascending = False)

City       Branch
Naypyitaw  C         5265.1765
Yangon     A         5057.1605
Mandalay   B         5057.0320
Name: gross income, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [27]:
invoices_by_category=df.pivot_table(index = 'Branch', columns = 'Product line', values = 'Invoice ID', aggfunc = 'count')
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [37]:
invoices_by_category['Electronic accessories'].sort_values(ascending = False).head(1)

Branch
A    60
Name: Electronic accessories, dtype: int64

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

In [ ]:
1. Чи спостерігається різниця в розмірі середнього чеку Total між Member і Normal клієнтами? 
Чи схильні Member клієнти купувати більше?
В цьому наборі даних покупців двох категорій є майже однакова кількість. З величини середнього чеку можна зробити висновок, що 
Members витрачають більше на одну покупку (на 3% більше ніж Normal покупці). 
Оскільки різниця не є великою, мережа може розглянути посилення переваг програм лояльності (бонуси, які спонукатимуть купити більше за раз, спеціальні акції, знижки за додатком).

In [21]:
df.groupby('Customer type')['Total'].agg(['sum','mean']).round(2)

                     sum    mean
Customer type
Member         164223.44  327.79
Normal         158743.30  318.12

In [19]:
df['Customer type'].value_counts()

Customer type
Member    501
Normal    499
Name: count, dtype: int64

In [ ]:
2. Яка кількість товару продана за кожною категорією та який валовий дохід вона принесла? 
Чи означає більша кількість проданого товару вищий дохід?

Electronic accessories продали найбільше одиниць (971), але найвищий прибуток отримав Food and beverages (2673.56), хоча там продано менше одиниць (952).
З наведених даних можна зробити висновок, що категорія-лідер за обсягом продажів не приносить найбільше прибутку.
Так бізнес може продовжувати розширювати асортимент категорії Food and beverages, а також виділити більше місця саме для цих товарів.
Категорію з найнижчими продажами Health and beauty можна детальніше дослідити та зрозуміти, чому низькі продажі: обмежений асортимент,
цінова політика (завищена ціна) або низький попит через специфіку супермаркету (людям більш схильні купляти товари для здоровʼя та краси в аптеках або спеціалізованих магазинах)

In [72]:
df.groupby('Product line')[['Quantity', 'gross income']].sum().sort_values(by = 'Quantity', ascending = False).round(2)

                        Quantity  gross income
Product line
Electronic accessories       971       2587.50
Food and beverages           952       2673.56
Sports and travel            920       2624.90
Home and lifestyle           911       2564.85
Fashion accessories          902       2586.00
Health and beauty            854       2342.56

In [ ]:
3. Яка кількість інвойсів була здійснена протягом трьох місяців та їхня динаміка в розрізі міст. 
Чи спостерігається певна сезонність? 
Оскільки цей датасет містить покупки тільки за три місяці, важко простежити повноцінну сезонність магазинів.
Дані, наведені нижче, допоможуть порівняти кількість покупок між місяцями та дати підказки для бізнесу, які акції або яка реклама були ефективними
Різниця в кількості інвойсів в Yangon виглядає найпомітнішою - зріст +35% з 94 до 127 покупок.

In [15]:
df['Date'] = pd.to_datetime(df['Date']) #тут скористалася допомогою АІ
df['Month'] = df['Date'].dt.month
df.Month.nunique()

3

In [16]:
df.pivot_table(index = 'City', columns = 'Month', values = 'Invoice ID', aggfunc = 'count')

Month        1    2    3
City
Mandalay   111  109  112
Naypyitaw  122  100  106
Yangon     119   94  127